services:

  pgserver:
    image: postgres:${POSTGRES_VERSION}
    hostname: pgserver
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    working_dir: /var/lib/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-dumps:/var/lib/postgresql/sql-dumps
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_ctl", "-D", "/var/lib/postgresql/data", "--status" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
    ports:
      - "8090:80"
    depends_on:
      - pgserver

volumes:
  postgres_data:
  pgadmin_data:
